/**
 * PM SHRI Kendriya Vidyalaya Portal — Cloud Configuration
 * ──────────────────────────────────────────────────────────
 * In production on Render:
 * This file is automatically generated at build/boot time by `build.js`
 * using the Environment Variables set in your Render Dashboard:
 * - SUPABASE_URL
 * - SUPABASE_ANON_KEY
 * - ADMIN_USERNAME
 * - ADMIN_PASSWORD
 *
 * For local offline development without Node/Render:
 * Sensible defaults are provided below.
 */

window.APP_CONFIG = {
  supabaseUrl: '',
  supabaseAnonKey: '',
  adminUsername: 'admin',
  adminPassword: 'kvs@2024',
  schoolName: 'PM SHRI Kendriya Vidyalaya Suranussi',
  isConfiguredViaEnv: false,
  buildTime: new Date().toISOString()
};

// Backwards compatibility alias for Supabase configuration
window.SUPABASE_CONFIG = {
  url: window.APP_CONFIG.supabaseUrl,
  anonKey: window.APP_CONFIG.supabaseAnonKey
};
