/**
 * AUTO-GENERATED BY build.js AT BUILD TIME
 * DO NOT EDIT DIRECTLY — Set environment variables on Render instead!
 *
 * Environment variables configured on Render:
 * - SUPABASE_URL
 * - SUPABASE_ANON_KEY
 * - ADMIN_USERNAME
 * - ADMIN_PASSWORD
 */

window.APP_CONFIG = {
  supabaseUrl: "",
  supabaseAnonKey: "",
  adminUsername: "admin",
  adminPassword: "kvs@2024",
  schoolName: "",
  isConfiguredViaEnv: false,
  buildTime: "2026-09-12T12:39:20.783Z"
};

// Backwards compatibility alias for Supabase config
window.SUPABASE_CONFIG = {
  url: window.APP_CONFIG.supabaseUrl,
  anonKey: window.APP_CONFIG.supabaseAnonKey
};
