/**
 * Build Script for Render / Static Hosting
 * ──────────────────────────────────────────
 * Ingests environment variables from Render (or local .env) and generates
 * `js/config.js` so frontend can connect to Supabase and authenticate admin.
 */

const fs = require('fs');
const path = require('path');

// Simple .env parser (avoids external dependency during build)
function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  const content = fs.readFileSync(filePath, 'utf-8');
  content.split(/\r?\n/).forEach(line => {
    line = line.trim();
    if (!line || line.startsWith('#')) return;
    const eqIdx = line.indexOf('=');
    if (eqIdx !== -1) {
      const key = line.substring(0, eqIdx).trim();
      let val = line.substring(eqIdx + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      if (!process.env[key]) {
        process.env[key] = val;
      }
    }
  });
}

// Check for local .env
loadEnvFile(path.join(__dirname, '.env'));

const supabaseUrl     = (process.env.SUPABASE_URL || '').trim();
const supabaseAnonKey = (process.env.SUPABASE_ANON_KEY || '').trim();
const adminUsername   = (process.env.ADMIN_USERNAME || 'admin').trim();
const adminPassword   = (process.env.ADMIN_PASSWORD || 'kvs@2024').trim();
const schoolName      = (process.env.SCHOOL_NAME || '').trim();

const mask = (str, visible = 4) => {
  if (!str) return '(not set)';
  if (str.length <= visible * 2) return '******';
  return str.substring(0, visible) + '...' + str.substring(str.length - visible);
};

console.log('--------------------------------------------------');
console.log('🚀 PM SHRI KV Suranussi — Build & Config Generator');
console.log('--------------------------------------------------');
console.log(`Supabase URL      : ${supabaseUrl ? supabaseUrl : '(not set — using local-storage mode)'}`);
console.log(`Supabase Anon Key : ${mask(supabaseAnonKey)}`);
console.log(`Admin Username    : ${adminUsername}`);
console.log(`Admin Password    : ${mask(adminPassword, 2)}`);
if (schoolName) console.log(`School Override   : ${schoolName}`);
console.log('--------------------------------------------------');

const configContent = `/**
 * AUTO-GENERATED BY build.js AT BUILD TIME
 * DO NOT EDIT DIRECTLY — Set environment variables on Render instead!
 *
 * Environment variables configured on Render:
 * - SUPABASE_URL
 * - SUPABASE_ANON_KEY
 * - ADMIN_USERNAME
 * - ADMIN_PASSWORD
 */

window.APP_CONFIG = {
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseAnonKey: ${JSON.stringify(supabaseAnonKey)},
  adminUsername: ${JSON.stringify(adminUsername)},
  adminPassword: ${JSON.stringify(adminPassword)},
  schoolName: ${JSON.stringify(schoolName)},
  isConfiguredViaEnv: ${Boolean(supabaseUrl && supabaseAnonKey)},
  buildTime: ${JSON.stringify(new Date().toISOString())}
};

// Backwards compatibility alias for Supabase config
window.SUPABASE_CONFIG = {
  url: window.APP_CONFIG.supabaseUrl,
  anonKey: window.APP_CONFIG.supabaseAnonKey
};
`;

const targetPath = path.join(__dirname, 'js', 'config.js');
fs.writeFileSync(targetPath, configContent, 'utf-8');
console.log(`✅ Generated: ${targetPath}`);
console.log('Build completed successfully.');
